import { sva } from 'styled-system/css'

/**
 * Calendar — co-located slot recipe.
 *
 * The date-by-date programme as a dark schedule board: header + counts, an
 * "Ongoing" exhibition card grid, the day-by-day agenda timeline, finished-edition
 * recap + shared archive Collapsible. Raw grays are the
 * documented dark-board exceptions; the card/gallery image filters are inlined
 * (were legacy `--card-*`/`--gallery-*` vars). State lives on data attributes:
 * `data-past` (runs/days), `data-on` (past toggle), `data-poster`
 * (event rows). The agenda's marker column is the `--marker-col` custom prop,
 * set responsively on the section.
 */
export const calendar = sva({
  slots: [
    'section',
    'inner',
    'layout',
    'header',
    'headerMain',
    'counts',
    'count',
    'pastToggle',
    'band',
    'bandLabel',
    'runs',
    'run',
    'runMedia',
    'runContent',
    'runName',
    'runFoot',
    'runRange',
    'empty',
    'emptyText',
    'emptyClear',
    'agenda',
    'day',
    'marker',
    'markerNode',
    'markerDay',
    'markerMeta',
    'markerMonth',
    'markerWeekday',
    'events',
    'event',
    'eventBody',
    'eventTop',
    'eventTime',
    'eventName',
    'nameButton',
    'eventDesc',
    'poster',
    'posterTag',
    'recap',
    'recapLine',
    'recapMark',
  ],
  base: {
    section: {
      // ground + rhythm come from `section({ ground: 'dark' })` in the component.
      // Shared links land on #program; offset past the tall top padding.
      scrollMarginTop: '[calc(token(spacing.lg) - token(spacing.sectionY))]',
      // Agenda date-marker column width — tracks the responsive `4xl` spacing
      // ramp so the column and the timeline spine (`agenda::before` `left`) stay
      // in lockstep and scale monotonically with the section rhythm.
      '--marker-col': 'token(spacing.4xl)',
    },
    inner: { layerStyle: 'sectionInner' },
    layout: { minWidth: '0' },

    header: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 'md',
      marginBottom: 'xl',
    },
    headerMain: { minWidth: '0' },

    counts: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 'md',
      marginTop: 'sm',
    },
    count: {
      fontFamily: 'body',
      fontSize: 'xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'white',
      fontVariantNumeric: 'tabular-nums',
    },
    pastToggle: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 'sm',
      minHeight: '[32px]',
      paddingBlock: 'xs',
      paddingInline: 'md',
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'gray.300',
      background: 'transparent',
      border: 'hairline',
      cursor: 'pointer',
      fontVariantNumeric: 'tabular-nums',
      transitionProperty: 'colors',
      transitionDuration: 'fast',
      transitionTimingFunction: 'quint',
      _hover: { color: 'white', borderColor: 'white' },
      _focusVisible: { outline: 'focus', outlineOffset: 'xs' },
      // On → the chartreuse "active" fill.
      '&[data-on=true]': {
        color: 'black',
        background: 'highlight',
        borderColor: 'highlight',
        _hover: { color: 'black', background: 'highlight', borderColor: 'highlight' },
      },
      _motionReduce: { transitionDuration: 'instant' },
    },

    // ---- Ongoing band — exhibition card grid ----
    band: {
      marginBottom: '2xl',
      paddingTop: 'lg',
      borderTop: 'hairline',
    },
    bandLabel: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'wide',
      fontWeight: 'semibold',
      color: 'highlight',
      marginBottom: 'md',
    },
    runs: {
      listStyle: 'none',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 300px), 1fr))',
      gap: 'md',
    },
    run: {
      display: 'flex',
      flexDirection: 'column',
      background: 'black',
      border: 'hairline',
      position: 'relative',
      // Gradient hover ring (masked to the hairline edge).
      _before: {
        content: '""',
        layerStyle: 'gradientBorder',
        padding: '[token(borderWidths.gradientRingHairline)]',
        transitionDuration: 'normal',
      },
      _hover: {
        '&::before': { opacity: 1, animationStyle: 'gradientBorder' },
        '& img': { filter: '[token(assets.developHover)]', transform: 'scale(1.03)' },
        '& a': { color: 'white' },
      },
      '& a:focus-visible': { color: 'white' },
      // Past de-emphasis (live edition only).
      '&[data-past=true]': {
        opacity: 0.42,
        transitionProperty: '[opacity]',
        transitionDuration: 'normal',
        transitionTimingFunction: 'quint',
      },
      '&[data-past=true]:hover': { opacity: 1 },
      _motionReduce: {
        '&:hover::before': { animation: 'none' },
      },
    },
    runMedia: {
      position: 'relative',
      aspectRatio: '3 / 2',
      overflow: 'hidden',
      background: 'gray.800',
      '& img': {
        objectFit: 'cover',
        filter: '[token(assets.developRest)]',
        transitionProperty: '[filter, transform]',
        transitionDuration: 'medium',
        transitionTimingFunction: 'quint',
      },
    },
    runContent: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'sm',
      padding: 'md',
      flex: '1',
      minWidth: '0',
    },
    runName: { textStyle: 'boardTitle' },
    runFoot: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 'md',
      marginTop: 'auto',
      paddingTop: 'sm',
    },
    runRange: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      color: 'muted',
    },

    // ---- Empty state ----
    empty: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: 'md',
      paddingBlock: '2xl',
      borderTop: 'hairline',
    },
    emptyText: {
      fontFamily: 'display',
      fontSize: 'lg',
      lineHeight: 'tight',
      color: 'gray.300',
    },
    emptyClear: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'white',
      background: 'transparent',
      border: 'none',
      paddingBottom: 'xs',
      borderBottom: 'hairline',
      cursor: 'pointer',
      transitionProperty: 'colors',
      transitionDuration: 'fast',
      transitionTimingFunction: 'quint',
      _hover: { color: 'action', borderColor: 'action' },
      _focusVisible: { outline: 'focus', outlineOffset: 'xs' },
    },

    // ---- Agenda timeline ----
    agenda: {
      listStyle: 'none',
      position: 'relative',
      // Timeline spine + marker column from tablet up.
      md: {
        _before: {
          content: '""',
          position: 'absolute',
          top: 'sm',
          bottom: 'sm',
          left: 'var(--marker-col)',
          width: '[1px]',
          background: 'divider',
        },
      },
    },
    day: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      paddingBlock: 'lg',
      borderTop: 'hairline',
      _first: { borderTop: 'none', paddingTop: '0' },
      '&[data-past=true]': {
        opacity: 0.42,
        transitionProperty: '[opacity]',
        transitionDuration: 'normal',
        transitionTimingFunction: 'quint',
      },
      '&[data-past=true]:hover': { opacity: 1 },
      md: {
        display: 'grid',
        gridTemplateColumns: 'var(--marker-col) 1fr',
        gap: '0',
        alignItems: 'start',
        position: 'relative',
      },
      xl: { paddingBlock: 'md' },
    },
    marker: {
      display: 'flex',
      alignItems: 'baseline',
      gap: 'md',
      md: {
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: 'sm',
        paddingRight: 'lg',
        textAlign: 'right',
        position: 'sticky',
        top: 'lg',
      },
    },
    markerNode: {
      display: 'none',
      md: {
        display: 'block',
        position: 'absolute',
        right: '-xs',
        top: '[9px]',
        width: '[8px]',
        height: '[8px]',
        background: 'white',
        borderRadius: 'circle',
      },
    },
    markerDay: {
      fontFamily: 'display',
      fontSize: '3xl',
      lineHeight: '[0.8]',
      color: 'white',
      fontVariantNumeric: 'tabular-nums',
      md: { fontSize: '2xl' },
    },
    markerMeta: {
      display: 'flex',
      alignItems: 'baseline',
      gap: 'sm',
      fontFamily: 'body',
      fontSize: 'xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      md: { flexDirection: 'column', alignItems: 'flex-end', gap: 'xs' },
    },
    markerMonth: { color: 'muted' },
    markerWeekday: { color: 'action' },
    events: {
      listStyle: 'none',
      display: 'flex',
      flexDirection: 'column',
      md: { paddingLeft: 'lg' },
    },

    // ---- Event row ----
    event: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      paddingBlock: 'md',
      borderTop: 'hairline',
      position: 'relative',
      _first: { borderTop: 'none' },
      _hover: {
        '& a': { color: 'action' },
        '& img': { filter: '[grayscale(0%) contrast(1)]', transform: 'scale(1.03)' },
      },
    },
    eventBody: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'sm',
      minWidth: '0',
      // Reserve the hover-float poster's column on poster rows (wide screens).
      '@media (hover: hover) and (pointer: fine) and (min-width: 1280px)': {
        '[data-poster=true] &': { paddingRight: '[calc(220px + token(spacing.lg))]' },
      },
    },
    eventTop: { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 'sm' },
    eventTime: {
      fontFamily: 'display',
      fontSize: 'sm',
      color: 'white',
      fontVariantNumeric: 'tabular-nums',
      letterSpacing: 'subtle',
    },
    eventName: { textStyle: 'boardTitle' },
    // The name link; its ::after stretches the hit target over the whole row.
    nameButton: {
      font: '[inherit]',
      color: '[inherit]',
      textAlign: 'left',
      textDecoration: 'none',
      background: 'transparent',
      border: 'none',
      padding: '0',
      cursor: 'pointer',
      transitionProperty: 'colors',
      transitionDuration: 'fast',
      transitionTimingFunction: 'quint',
      _after: { content: '""', position: 'absolute', inset: '0', zIndex: '1' },
      _focusVisible: {
        color: 'action',
        outline: 'focus',
        outlineOffset: 'xs',
      },
      _motionReduce: { transitionDuration: 'instant' },
    },
    eventDesc: {
      fontFamily: 'body',
      fontSize: 'sm',
      lineHeight: 'body',
      color: 'body',
      maxWidth: 'measure',
      // Two-line teaser; Panda's lineClamp expands the full -webkit-box clamp.
      lineClamp: '2',
    },
    // Touch/narrow: inline portrait thumbnail. Wide hover-capable: float (below).
    poster: {
      position: 'relative',
      aspectRatio: '3 / 4',
      width: 'full',
      maxWidth: '[260px]',
      overflow: 'hidden',
      background: 'gray.800',
      '& img': {
        objectFit: 'cover',
        filter: '[grayscale(100%) contrast(1.1)]',
        transitionProperty: '[filter, transform]',
        transitionDuration: 'medium',
        transitionTimingFunction: 'quint',
      },
      '@media (hover: hover) and (pointer: fine) and (min-width: 1280px)': {
        position: 'absolute',
        top: 'md',
        right: '0',
        width: '[220px]',
        maxWidth: '[none]',
        opacity: 0,
        transform: 'translateX(20px)',
        transitionProperty: '[opacity, transform]',
        transitionDuration: 'normal',
        transitionTimingFunction: 'expo',
        pointerEvents: 'none',
        zIndex: '3',
        '[data-poster=true]:hover &': { opacity: 1, transform: 'translateX(0)' },
      },
      _motionReduce: {
        '@media (hover: hover) and (pointer: fine) and (min-width: 1280px)': {
          transitionProperty: '[opacity]',
          transitionDuration: 'normal',
          transitionTimingFunction: 'quint',
          transform: 'none',
          '[data-poster=true]:hover &': { transform: 'none' },
        },
      },
    },
    posterTag: {
      textStyle: 'metaLabel',
      display: 'none',
      alignItems: 'center',
      gap: 'sm',
      transitionProperty: 'colors',
      transitionDuration: 'fast',
      transitionTimingFunction: 'quint',
      _before: { content: '""', width: '[7px]', height: '[9px]', background: 'current' },
      '@media (hover: hover) and (pointer: fine) and (min-width: 1280px)': {
        display: 'inline-flex',
        '[data-poster=true]:hover &': { color: 'action' },
      },
    },

    // ---- Finished-edition recap ----
    recap: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: 'md',
      marginTop: 'sm',
    },
    recapLine: { fontFamily: 'body', fontSize: 'base', lineHeight: 'body', color: 'body' },
    recapMark: { color: 'white', fontWeight: 'semibold' },
  },
})
