import { sva } from 'styled-system/css'

export const editionCard = sva({
  slots: [
    'root',
    'media',
    'image',
    'badgeRow',
    'badgeStack',
    'year',
    'content',
    'themeRow',
    'themeTape',
    'meta',
    'metaItem',
    'status',
  ],
  base: {
    root: {
      height: '100%',
      overflow: 'visible',
      _focusVisible: { outline: '2px solid token(colors.action)', outlineOffset: '4px' },
      '&[data-current=true]': { cursor: 'default', borderColor: 'highlight' },
      '&[data-upcoming]': {
        cursor: 'default',
        opacity: '0.58',
        filter: 'grayscale(1)',
        '& h2': { color: 'muted' },
        '& .badge': {
          background: 'gray.900',
          borderColor: 'gray.700',
          color: 'gray.400',
          boxShadow: 'none',
        },
      },
    },
    media: {
      position: 'relative',
      width: '100%',
      overflow: 'hidden',
      background: 'gray.900',
      _after: {
        content: '""',
        position: 'absolute',
        inset: '0',
        background: 'linear-gradient(180deg, rgb(0 0 0 / 0.5), transparent 30%, rgb(0 0 0 / 0.55))',
        pointerEvents: 'none',
        zIndex: '1',
      },
    },
    image: {
      objectFit: 'cover',
      background: 'gray.900',
      filter: 'grayscale(100%) brightness(0.7)',
      transform: 'scale(1.01)',
      transition:
        'filter {durations.reveal} {easings.expo}, transform {durations.entrance} {easings.expo}',
      'a:hover &, a:focus-visible &': {
        filter: 'grayscale(30%) brightness(1)',
        transform: 'scale(1.05)',
      },
    },
    badgeRow: {
      position: 'absolute',
      top: 'md',
      left: 'md',
      right: 'md',
      zIndex: '2',
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 'xs',
    },
    badgeStack: {},
    year: {},
    content: {
      position: 'relative',
      zIndex: '1',
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      marginTop: '-3rem',
      padding: 'md',
    },
    themeRow: {
      position: 'relative',
      display: 'inline-flex',
      maxWidth: '100%',
    },
    themeTape: {},
    meta: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: 'xs',
      margin: '0',
      padding: 'md 0 0',
      borderTop: 'hairline',
      color: 'body',
      md: { gridTemplateColumns: 'repeat(3, minmax(0, 1fr))' },
    },
    metaItem: {
      display: 'grid',
      gap: '2xs',
      minWidth: '0',
      '& dt': { textStyle: 'metaLabel' },
      '& dd': { margin: '0', fontSize: 'sm', lineHeight: 'body', textWrap: 'pretty' },
    },
    status: { alignSelf: 'flex-start' },
  },
  variants: {
    media: {
      image: {},
      none: {
        root: { padding: '0', minHeight: '0' },
        content: { marginTop: '0', padding: '0', flex: '0 0 auto' },
        badgeRow: {
          position: 'static',
          right: 'auto',
          flex: '0 0 auto',
        },
        themeRow: {
          minWidth: '0',
        },
        themeTape: {
          paddingLeft: '6.25rem',
        },
        badgeStack: {
          position: 'absolute',
          top: '50%',
          left: '0.6em',
          zIndex: '2',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'flex-start',
          gap: '2xs',
          transform: 'translateY(-50%)',
        },
      },
    },
    size: {
      lg: { media: { aspectRatio: '21 / 9' } },
      md: { media: { aspectRatio: { base: '4 / 3', md: '16 / 10' } } },
      sm: {
        root: { minHeight: '0' },
      },
    },
  },
  defaultVariants: { media: 'image', size: 'md' },
})
