import { sva } from 'styled-system/css'

export const editionCard = sva({
  slots: [
    'root',
    'plate',
    'frame',
    'image',
    'body',
    'link',
    'head',
    'title',
    'theme',
    'prefix',
    'count',
    'prose',
  ],
  base: {
    root: {
      position: 'relative',
      display: 'grid',
      gridTemplateColumns: 'auto minmax(0, 1fr)',
      gridTemplateAreas: '"plate link"',
      columnGap: 'md',
      rowGap: 'md',
      alignItems: 'start',
      color: 'body',
      md: {
        gridTemplateColumns: 'minmax(0, 1fr)',
        gridTemplateAreas: '"plate" "body"',
        columnGap: 'xl',
        rowGap: 'lg',
        alignItems: 'stretch',
      },
      lg: {
        gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
        alignItems: 'center',
      },
    },
    plate: {
      gridArea: 'plate',
      position: 'relative',
      width: { base: 'clamp(72px, 22vw, 104px)', md: '100%' },
      border: 'hairline',
      aspectRatio: { base: '1 / 1', md: '16 / 9', lg: '3 / 2' },
    },
    frame: {
      position: 'absolute',
      inset: '0',
      overflow: 'hidden',
      background: 'gray.900',
    },
    image: {
      objectFit: 'cover',
      background: 'gray.900',
      filter: 'token(assets.color)',
      transform: 'scale(1.01)',
      transition: 'develop',
      'article:has([data-card-link]:hover) &, article:has([data-card-link]:focus-visible) &': {
        filter: 'token(assets.colorHover)',
        transform: 'scale(1.05)',
      },
    },
    body: {
      gridArea: 'body',
      display: { base: 'contents', md: 'flex' },
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: 'md',
    },
    link: {
      gridArea: 'link',
      pressable: 'dim',
      minWidth: '0',
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      color: 'body',
      textDecoration: 'none',
      _after: { content: '""', position: 'absolute', inset: '0' },
    },
    head: { minWidth: '0', display: 'flex', flexDirection: 'column', gap: 'xs' },
    title: { fontVariantNumeric: 'tabular-nums' },
    // Themes are single hashtag words with no wrap opportunity of their own.
    theme: { overflowWrap: 'anywhere' },
    prefix: {
      color: 'muted',
      transition: 'interactive',
      'a:hover &, a:focus-visible &': { color: 'action' },
    },
    count: { color: 'heading' },
    prose: {
      position: 'relative',
      display: { base: 'none', lg: 'block' },
      maxWidth: 'measure',
    },
  },
  variants: {
    media: {
      left: { root: { lg: { gridTemplateAreas: '"plate body"' } } },
      right: { root: { lg: { gridTemplateAreas: '"body plate"' } } },
    },
  },
  defaultVariants: { media: 'left' },
})
