/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SftfBanner = {
  tag: string;
  title: string;
  description: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CarouselImageImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type SlideFeaturedStack = {
  _type: "slideFeaturedStack";
  images: Array<{
    image: CarouselImageImage;
    caption: string;
    _type: "carouselImage";
    _key: string;
  }>;
};

export type SlideTrio = {
  _type: "slideTrio";
  images: Array<{
    image: CarouselImageImage;
    caption: string;
    _type: "carouselImage";
    _key: string;
  }>;
};

export type SlideFeaturedPortrait = {
  _type: "slideFeaturedPortrait";
  images: Array<{
    image: CarouselImageImage;
    caption: string;
    _type: "carouselImage";
    _key: string;
  }>;
};

export type SlideDuo = {
  _type: "slideDuo";
  images: Array<{
    image: CarouselImageImage;
    caption: string;
    _type: "carouselImage";
    _key: string;
  }>;
};

export type SlideFull = {
  _type: "slideFull";
  images: Array<{
    image: CarouselImageImage;
    caption: string;
    _type: "carouselImage";
    _key: string;
  }>;
};

export type VenueEntry = {
  _type: "venueEntry";
  group: string;
  subgroup: string;
  name: string;
  program: string;
};

export type ProgramData = {
  _type: "programData";
  dates: string;
  blocks: Array<{
    type:
      | "Exhibition"
      | "Main Exhibition"
      | "Student Exhibition"
      | "Opening Event"
      | "Special Event"
      | "Film Program"
      | "Talks & Workshops";
    title: string;
    dates: string;
    description: string;
    location?: string;
    format?: "Roundtable" | "Workshop" | "Open Studios";
    column: 1 | 2;
    _type: "programBlock";
    _key: string;
  }>;
  films?: Array<{
    date: string;
    title: string;
    note?: string;
    _type: "programFilm";
    _key: string;
  }>;
  sftfBanner: SftfBanner;
};

export type CreditText = {
  _type: "creditText";
  type: "primary" | "partner" | "secondary";
  label: string;
  value: string;
};

export type OrganizationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "organization";
};

export type CreditOrgList = {
  _type: "creditOrgList";
  type: "primary" | "partner" | "secondary";
  label: string;
  organizations: Array<
    {
      _key: string;
    } & OrganizationReference
  >;
};

export type CreditOrg = {
  _type: "creditOrg";
  type: "primary" | "partner" | "secondary";
  label: string;
  organization: OrganizationReference;
  detail?: string;
};

export type Organization = {
  _id: string;
  _type: "organization";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  url?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ArtistReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "artist";
};

export type Edition = {
  _id: string;
  _type: "edition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year: number;
  theme: string;
  themeHighlight: string;
  title: string;
  dateTape: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  thumbImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  manifesto: {
    title: string;
    highlight: string;
    body: string;
  };
  themeSection: {
    body: string;
  };
  artists: Array<
    {
      _key: string;
    } & ArtistReference
  >;
  venues?: Array<
    {
      _key: string;
    } & VenueEntry
  >;
  program?: ProgramData;
  carousel?: Array<
    | ({
        _key: string;
      } & SlideFull)
    | ({
        _key: string;
      } & SlideDuo)
    | ({
        _key: string;
      } & SlideFeaturedPortrait)
    | ({
        _key: string;
      } & SlideTrio)
    | ({
        _key: string;
      } & SlideFeaturedStack)
  >;
  credits: Array<
    | ({
        _key: string;
      } & CreditOrg)
    | ({
        _key: string;
      } & CreditOrgList)
    | ({
        _key: string;
      } & CreditText)
  >;
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  shortBio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  discipline?: string;
  country?: string;
  externalLinks?: Array<{
    label: string;
    url: string;
    _type: "externalLink";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail: string;
  instagramUrl?: string;
  facebookUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SftfBanner
  | SanityImageAssetReference
  | CarouselImageImage
  | SlideFeaturedStack
  | SlideTrio
  | SlideFeaturedPortrait
  | SlideDuo
  | SlideFull
  | VenueEntry
  | ProgramData
  | CreditText
  | OrganizationReference
  | CreditOrgList
  | CreditOrg
  | Organization
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ArtistReference
  | Edition
  | Artist
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    contactEmail,    instagramUrl,    facebookUrl  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      contactEmail: null;
      instagramUrl: null;
      facebookUrl: null;
    }
  | {
      contactEmail: string;
      instagramUrl: string | null;
      facebookUrl: string | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: ARTISTS_QUERY
// Query: *[_type == "artist" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    portrait,    shortBio,    discipline,    country  }
export type ARTISTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  portrait: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  shortBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  discipline: string | null;
  country: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ARTIST_BY_SLUG_QUERY
// Query: *[_type == "artist" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    portrait,    shortBio,    discipline,    country,    externalLinks  }
export type ARTIST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  portrait: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  shortBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  discipline: string | null;
  country: string | null;
  externalLinks: Array<{
    label: string;
    url: string;
    _type: "externalLink";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EDITION_YEARS_QUERY
// Query: *[_type == "edition" && defined(year)] | order(year desc).year
export type EDITION_YEARS_QUERY_RESULT = Array<number>;

// Source: src/sanity/lib/queries.ts
// Variable: EDITION_BY_YEAR_QUERY
// Query: *[_type == "edition" && year == $year][0] {    _id,    year,    title,    theme,    themeHighlight,    dateTape,    heroImage,    thumbImage,    manifesto,    themeSection,    "artists": artists[]->name,    venues,    program,    carousel[] {      _type,      images[] {        caption,        image      }    },    credits[] {      _type,      type,      label,      detail,      value,      organization->{        name,        logo      },      organizations[]->{        name,        logo      }    }  }
export type EDITION_BY_YEAR_QUERY_RESULT = {
  _id: string;
  year: number;
  title: string;
  theme: string;
  themeHighlight: string;
  dateTape: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  thumbImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  manifesto: {
    title: string;
    highlight: string;
    body: string;
  };
  themeSection: {
    body: string;
  };
  artists: Array<string>;
  venues: Array<
    {
      _key: string;
    } & VenueEntry
  > | null;
  program: ProgramData | null;
  carousel: Array<
    | {
        _type: "slideDuo";
        images: Array<{
          caption: string;
          image: CarouselImageImage;
        }>;
      }
    | {
        _type: "slideFeaturedPortrait";
        images: Array<{
          caption: string;
          image: CarouselImageImage;
        }>;
      }
    | {
        _type: "slideFeaturedStack";
        images: Array<{
          caption: string;
          image: CarouselImageImage;
        }>;
      }
    | {
        _type: "slideFull";
        images: Array<{
          caption: string;
          image: CarouselImageImage;
        }>;
      }
    | {
        _type: "slideTrio";
        images: Array<{
          caption: string;
          image: CarouselImageImage;
        }>;
      }
  > | null;
  credits: Array<
    | {
        _type: "creditOrg";
        type: "partner" | "primary" | "secondary";
        label: string;
        detail: string | null;
        value: null;
        organization: {
          name: string;
          logo: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          } | null;
        };
        organizations: null;
      }
    | {
        _type: "creditOrgList";
        type: "partner" | "primary" | "secondary";
        label: string;
        detail: null;
        value: null;
        organization: null;
        organizations: Array<{
          name: string;
          logo: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          } | null;
        }>;
      }
    | {
        _type: "creditText";
        type: "partner" | "primary" | "secondary";
        label: string;
        detail: null;
        value: string;
        organization: null;
        organizations: null;
      }
  >;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    contactEmail,\n    instagramUrl,\n    facebookUrl\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "artist" && defined(slug.current)] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    portrait,\n    shortBio,\n    discipline,\n    country\n  }\n': ARTISTS_QUERY_RESULT;
    '\n  *[_type == "artist" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    portrait,\n    shortBio,\n    discipline,\n    country,\n    externalLinks\n  }\n': ARTIST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "edition" && defined(year)] | order(year desc).year\n': EDITION_YEARS_QUERY_RESULT;
    '\n  *[_type == "edition" && year == $year][0] {\n    _id,\n    year,\n    title,\n    theme,\n    themeHighlight,\n    dateTape,\n    heroImage,\n    thumbImage,\n    manifesto,\n    themeSection,\n    "artists": artists[]->name,\n    venues,\n    program,\n    carousel[] {\n      _type,\n      images[] {\n        caption,\n        image\n      }\n    },\n    credits[] {\n      _type,\n      type,\n      label,\n      detail,\n      value,\n      organization->{\n        name,\n        logo\n      },\n      organizations[]->{\n        name,\n        logo\n      }\n    }\n  }\n': EDITION_BY_YEAR_QUERY_RESULT;
  }
}
