import { sva } from 'styled-system/css'

export const editionsNav = sva({
  slots: [
    'band',
    'inner',
    'grid',
    'cell',
    'head',
    'year',
    'prefix',
    'tag',
    'theme',
    'clip',
    'face',
    'faceIn',
    'prefixIn',
  ],
  base: {
    band: { background: 'surface', paddingBlock: 'xl' },
    inner: { layerStyle: 'sectionInner' },
    grid: {
      display: 'grid',
      gridTemplateColumns: {
        base: 'minmax(0, 1fr)',
        md: 'repeat(2, minmax(0, 1fr))',
        xl: 'repeat(3, minmax(0, 1fr))',
      },
      borderBlockStart: 'hairline',
      borderInlineStart: 'hairline',
      marginBlockStart: 'lg',
    },
    cell: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'sm',
      minWidth: '0',
      padding: '[calc(token(spacing.lg) * 0.75)]',
      background: 'surface',
      position: 'relative',
      borderBlockEnd: 'hairline',
      borderInlineEnd: 'hairline',
    },
    head: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      columnGap: 'md',
      rowGap: 'sm',
    },
    year: { margin: '0', textStyle: 'heading', color: 'heading' },
    prefix: { color: 'muted' },
    tag: { marginInlineStart: 'auto' },
    theme: { flexWrap: 'wrap', overflowWrap: 'anywhere' },
    clip: { display: 'block', position: 'relative', overflow: 'clip', margin: '0' },
    face: { display: 'block', transition: 'develop', 'p > &': { transitionDelay: 'stagger' } },
    faceIn: {
      display: 'block',
      position: 'absolute',
      insetInline: '0',
      top: '[100%]',
      color: 'heading',
      transition: 'develop',
      'p > &': { transitionDelay: 'stagger' },
    },
    prefixIn: { color: 'action' },
  },
  variants: {
    status: {
      live: {
        cell: { pressable: 'fill' },
        theme: { '@media (hover: none)': { '& > span': { color: 'action' } } },
        face: {
          '@media (hover: hover)': { 'a:hover &': { translate: '[0 -100%]' } },
          'a:focus-visible &': { translate: '[0 -100%]' },
        },
        faceIn: {
          '@media (hover: hover)': { 'a:hover &': { translate: '[0 -100%]' } },
          'a:focus-visible &': { translate: '[0 -100%]' },
          'a:active & span span': { color: 'highlight', transitionDuration: '0ms' },
        },
      },
      current: {
        cell: { cursor: 'default' },
        tag: {
          position: 'absolute',
          insetBlockStart: '[-1px]',
          insetInlineEnd: '[calc(token(spacing.lg) * 0.75)]',
          paddingInline: '[12px]',
          paddingBlockStart: '[10px]',
          paddingBlockEnd: '[7px]',
          borderWidth: '0',
          boxShadow: 'litEdge',
        },
      },
      announced: {
        cell: { cursor: 'default' },
        year: { color: 'body' },
      },
    },
  },
  defaultVariants: { status: 'live' },
})
