import { defineSlotRecipe } from '@/design-system/define-recipe'

// Full-screen image viewer: layout, controls, and gesture feedback. Dialog owns
// the modal state and shell; the backdrop alpha + drag transform stay inline.
export const lightbox = defineSlotRecipe({
  className: 'lightbox',
  jsx: ['Lightbox'],
  slots: [
    'lightbox',
    'bar',
    'barNav',
    'caption',
    'close',
    'stage',
    'imageLayer',
    'image',
    'dissolve',
    'preload',
    'preloadFrame',
  ],
  base: {
    lightbox: {
      position: 'relative',
      display: 'grid',
      gridTemplateRows: '[minmax(0, 1fr) auto]',
      '3xl': {
        gridTemplateRows: '[minmax(0, 1fr)]',
        gridTemplateColumns: '[minmax(0, 1fr) auto]',
      },
      width: 'full',
      height: 'full',
      background: 'surface.scrim',
      overscrollBehavior: 'contain',
    },
    bar: {
      display: 'grid',
      gridTemplateColumns: '[minmax(0, 1fr) auto]',
      alignItems: 'center',
      gap: 'md',
      height: 'touch',
      paddingInline: 'sm',
      background: 'surface',
      color: 'heading',
      '3xl': {
        gridTemplateColumns: '[minmax(0, 1fr)]',
        gridTemplateRows: '[auto minmax(0, 1fr) auto]',
        alignItems: 'stretch',
        width: '[200px]',
        height: 'full',
        paddingInline: '0',
        paddingBlock: 'sm',
        borderInlineStart: 'hairline',
      },
    },
    barNav: {
      display: 'flex',
      alignItems: 'center',
      gap: 'xs',
      justifySelf: 'end',
      '3xl': { gridRow: '3', justifySelf: 'start' },
    },
    caption: {
      fontFamily: 'display',
      fontSize: 'sm',
      textTransform: 'uppercase',
      textAlign: 'start',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      paddingInline: '[calc((token(sizes.touch) - 20px) / 2)]',
      '3xl': {
        gridRow: '2',
        alignSelf: 'end',
        marginBlockEnd: 'lg',
        maxHeight: 'full',
        overflowY: 'auto',
        textOverflow: 'clip',
        whiteSpace: 'normal',
        lineHeight: '1.3',
        '& > span': { display: 'block' },
      },
    },
    close: {
      position: 'absolute',
      top: 'sm',
      right: 'sm',
      zIndex: '1',
      '3xl': { position: 'static', gridRow: '1', justifySelf: 'end' },
    },
    stage: {
      position: 'relative',
      minHeight: '0',
      marginBlockStart: '[calc(token(sizes.touch) + token(spacing.sm) * 2)]',
      '3xl': { marginBlockStart: '0' },
      overflow: 'hidden',
      cursor: 'zoom-out',
      touchAction: 'none',
      willChange: 'transform, opacity',
    },
    imageLayer: { position: 'absolute', inset: '0' },
    image: { objectFit: 'contain', userSelect: 'none' },
    dissolve: {
      position: 'absolute',
      inset: '0',
      pointerEvents: 'none',
      overflow: 'hidden',
    },

    // Off-screen N±1 prefetch of optimized variants.
    preload: {
      position: 'fixed',
      top: '0',
      left: '0',
      width: '[1px]',
      height: '[1px]',
      overflow: 'hidden',
      opacity: 0,
      pointerEvents: 'none',
      zIndex: '[-1]',
    },
    preloadFrame: { position: 'relative', width: '[100vw]', height: '[100vh]' },
  },
})
