import { sva } from 'styled-system/css'

export const nameCloudSheet = sva({
  slots: ['root', 'panel', 'inner', 'head', 'label', 'close', 'name', 'years', 'year'],
  base: {
    root: { position: 'relative' },
    panel: {
      position: 'fixed',
      insetInline: '0',
      insetBlockEnd: '0',
      zIndex: 'modal',
      background: 'surface',
      borderBlockStart: 'hairline',
      boxShadow: 'litEdge',
      opacity: '0',
      translate: '[0 100%]',
      pointerEvents: 'none',
      transition: 'develop',
      '&[data-open]': { opacity: '1', translate: '[0 0]', pointerEvents: 'auto' },
    },
    inner: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'sm',
      maxWidth: 'maxWidth',
      marginInline: 'auto',
      paddingInline: 'gutter',
      paddingBlockStart: 'md',
      paddingBlockEnd: '[calc(token(spacing.md) + env(safe-area-inset-bottom))]',
    },
    head: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 'md' },
    label: { textStyle: 'label', color: 'muted' },
    close: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      marginInlineEnd: '[calc(token(spacing.sm) * -1)]',
      border: 'none',
      background: 'transparent',
      color: 'muted',
      cursor: 'pointer',
    },
    name: { textStyle: 'heading', color: 'heading' },
    years: { display: 'flex', flexWrap: 'wrap', gap: 'sm', listStyleType: 'none' },
    year: {
      textStyle: 'caption',
      color: 'body',
      border: 'hairline',
      paddingBlock: 'xs',
      paddingInline: 'sm',
      whiteSpace: 'nowrap',
    },
  },
})
