import { sva } from 'styled-system/css'

export const workCarousel = sva({
  slots: [
    'root',
    'controls',
    'counter',
    'track',
    'slide',
    'cover',
    'thumbs',
    'thumb',
    'title',
    'meta',
    'metaTerm',
    'description',
  ],
  base: {
    root: { display: 'flex', flexDirection: 'column', gap: 'lg' },
    controls: { display: 'flex', alignItems: 'center', gap: 'md' },
    counter: { textStyle: 'label', color: 'muted', fontVariantNumeric: 'tabular-nums' },
    track: {
      display: 'flex',
      overflowX: 'auto',
      scrollSnapType: 'x',
      scrollSnapStrictness: 'mandatory',
      overscrollBehaviorX: 'contain',
      scrollbar: 'hidden',
      listStyleType: 'none',
    },
    slide: {
      flex: '[0 0 100%]',
      scrollSnapAlign: 'start',
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      minWidth: '0',
      paddingInlineEnd: 'md',
    },
    cover: {
      position: 'relative',
      overflow: 'hidden',
      width: 'full',
      aspectRatio: '4 / 5',
      '& img': { objectFit: 'contain' },
    },
    thumbs: { display: 'flex', flexWrap: 'wrap', gap: 'xs', listStyleType: 'none' },
    thumb: {
      position: 'relative',
      overflow: 'hidden',
      width: '[3.5rem]',
      aspectRatio: '1',
      opacity: 0.5,
      '&[aria-pressed=true]': { opacity: 1 },
    },
    title: { textStyle: 'heading', color: 'heading' },
    meta: {
      display: 'grid',
      gridTemplateColumns: 'auto 1fr',
      columnGap: 'md',
      rowGap: 'xs',
      textStyle: 'caption',
      color: 'body',
    },
    metaTerm: { color: 'muted' },
    description: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      maxWidth: 'measure',
      textStyle: 'body',
      color: 'body',
    },
  },
})
