import { sva } from 'styled-system/css'

export const workCarousel = sva({
  slots: [
    'root',
    'controls',
    'counter',
    'arrows',
    'track',
    'slide',
    'media',
    'details',
    'cover',
    'thumbs',
    'thumb',
    'title',
    'meta',
    'metaTerm',
    'description',
  ],
  base: {
    root: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'lg',
      borderTop: 'hairline',
      paddingTop: 'md',
    },
    controls: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 'md',
    },
    arrows: { display: 'flex' },
    counter: { textStyle: 'label', color: 'muted', fontVariantNumeric: 'tabular-nums' },
    track: {
      display: 'flex',
      overflowX: 'auto',
      scrollSnapType: 'x',
      scrollSnapStrictness: 'mandatory',
      overscrollBehaviorX: 'contain',
      scrollbar: 'hidden',
      listStyleType: 'none',
    },
    slide: {
      flex: '[0 0 100%]',
      scrollSnapAlign: 'start',
      display: 'grid',
      alignContent: 'start',
      columnGap: 'xl',
      rowGap: 'md',
      minWidth: '0',
      paddingInlineEnd: 'md',
    },
    media: {
      gridArea: 'media',
      display: 'flex',
      flexDirection: 'column',
      gap: 'xs',
      minWidth: '0',
    },
    details: {
      gridArea: 'details',
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      minWidth: '0',
    },
    cover: {
      position: 'relative',
      overflow: 'hidden',
      width: 'full',
      aspectRatio: '4 / 5',
      maxHeight: { md: '[80svh]' },
      '& img': { objectFit: 'contain' },
    },
    thumbs: { display: 'flex', flexWrap: 'wrap', gap: 'xs', listStyleType: 'none' },
    thumb: {
      position: 'relative',
      overflow: 'hidden',
      width: '[3.5rem]',
      aspectRatio: '1',
      opacity: 0.5,
      '&[aria-pressed=true]': { opacity: 1 },
    },
    title: { gridArea: 'title', textStyle: 'heading', color: 'heading' },
    meta: {
      display: 'grid',
      gridTemplateColumns: 'auto 1fr',
      columnGap: 'md',
      rowGap: 'xs',
      textStyle: 'caption',
      color: 'body',
    },
    metaTerm: { color: 'muted' },
    description: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      maxWidth: 'measure',
      textStyle: 'body',
      color: 'body',
    },
  },
  variants: {
    withMedia: {
      true: {
        slide: {
          gridTemplateAreas: {
            base: '"title" "media" "details"',
            md: '"title media" "details media"',
          },
          gridTemplateColumns: { md: '[minmax(0, 2fr) minmax(0, 3fr)]' },
          gridTemplateRows: { md: '[auto 1fr]' },
        },
      },
      false: {
        slide: { gridTemplateAreas: '"title" "details"' },
      },
    },
  },
})
