import { sva } from 'styled-system/css'

export const workList = sva({
  slots: [
    'root',
    'controls',
    'counter',
    'arrows',
    'track',
    'entry',
    'article',
    'title',
    'plate',
    'stage',
    'views',
    'view',
    'text',
    'facts',
    'fact',
    'term',
    'value',
    'description',
  ],
  base: {
    controls: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 'md',
      borderTop: 'hairline',
    },
    counter: { textStyle: 'label', color: 'muted', fontVariantNumeric: 'tabular-nums' },
    arrows: { display: 'flex', marginInlineEnd: '-14px' },
    track: {
      position: 'relative',
      display: 'flex',
      alignItems: 'flex-start',
      columnGap: 'xl',
      overflowX: 'auto',
      scrollSnapType: 'x',
      scrollSnapStrictness: 'mandatory',
      overscrollBehaviorX: 'contain',
      scrollbar: 'hidden',
      listStyleType: 'none',
    },
    entry: {
      flex: '0 0 100%',
      minWidth: '0',
      scrollSnapAlign: 'start',
      paddingBlock: { base: 'xl', lg: '2xl' },
    },
    article: {
      display: 'grid',
      columnGap: 'xl',
      rowGap: 'lg',
      alignItems: 'start',
    },
    title: {
      gridArea: 'title',
      textStyle: 'detailTitle',
      color: 'heading',
    },
    plate: {
      gridArea: 'plate',
      containerType: 'inline-size',
      display: 'flex',
      flexDirection: 'column',
      gap: 'sm',
      minWidth: '0',
    },
    stage: {
      '--stage-cap': { base: '72svh', lg: 'min(82svh, 960px)' },
      '--stage-floor': '0',
      '--stage-h': 'min(var(--stage-cap), 100cqi * max(var(--stage-ratio), var(--stage-floor)))',
      position: 'relative',
      overflow: 'hidden',
      width: 'min(100%, var(--stage-h) * var(--view-ratio))',
      height: 'var(--stage-h)',
      marginInline: { base: 'auto', lg: '0' },
      cursor: 'zoom-in',
    },
    views: { display: 'flex', flexWrap: 'wrap', gap: 'xs', listStyleType: 'none' },
    view: {
      position: 'relative',
      overflow: 'hidden',
      width: { base: '3.5rem', lg: '4rem' },
      aspectRatio: '1',
      opacity: 0.45,
      transition: 'interactive',
      _hover: { opacity: 1 },
      '&[aria-pressed=true]': {
        opacity: 1,
        _after: {
          content: '""',
          position: 'absolute',
          insetInline: '0',
          bottom: '0',
          height: '2px',
          background: 'highlight',
        },
      },
    },
    text: {
      gridArea: 'text',
      display: 'flex',
      flexDirection: 'column',
      gap: 'lg',
      minWidth: '0',
    },
    facts: { borderBottom: 'hairline' },
    fact: {
      display: 'grid',
      gridTemplateColumns: 'minmax(5.5rem, 2fr) minmax(0, 5fr)',
      alignItems: 'baseline',
      columnGap: 'md',
      paddingBlock: 'sm',
      borderTop: 'hairline',
    },
    term: { textStyle: 'label', color: 'muted' },
    value: { textStyle: 'body', color: 'heading', fontVariantNumeric: 'tabular-nums' },
    description: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      maxWidth: 'measure',
      textStyle: 'body',
      color: 'body',
    },
  },
  variants: {
    views: {
      single: {},
      multiple: {
        stage: { '--stage-floor': { base: '0.75', lg: '0.7' } },
      },
    },
    withMedia: {
      true: {
        article: {
          gridTemplateAreas: { base: '"title" "plate" "text"', lg: '"plate title" "plate text"' },
          gridTemplateColumns: { lg: 'minmax(0, 8fr) minmax(0, 4fr)' },
          gridTemplateRows: { lg: 'auto 1fr' },
        },
      },
      false: {
        article: { gridTemplateAreas: '"title" "text"', maxWidth: 'measure' },
      },
    },
  },
  defaultVariants: { views: 'single', withMedia: true },
})

export const workIndex = sva({
  slots: ['root', 'picker', 'select', 'chevron', 'list', 'link', 'title', 'year'],
  base: {
    root: { minWidth: '0' },
    picker: { position: 'relative', display: { lg: 'none' } },
    select: {
      appearance: 'none',
      width: '100%',
      minHeight: 'touch',
      paddingBlock: 'sm',
      paddingInlineStart: '0',
      paddingInlineEnd: '2rem',
      borderBlock: 'hairline',
      borderInline: 'none',
      background: 'transparent',
      colorScheme: 'dark',
      textStyle: 'body',
      color: 'heading',
      cursor: 'pointer',
      transition: 'interactive',
      _hover: { color: 'action' },
      _focusVisible: { outline: 'focus', outlineOffset: 'focusInset' },
      '& option': { background: 'black', color: 'white' },
    },
    chevron: {
      position: 'absolute',
      insetInlineEnd: '0',
      top: '50%',
      transform: 'translateY(-50%)',
      color: 'heading',
      pointerEvents: 'none',
    },
    list: {
      display: { base: 'none', lg: 'block' },
      listStyleType: 'none',
      borderBottom: { lg: 'hairline' },
    },
    link: {
      display: 'flex',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      gap: 'md',
      width: '100%',
      minHeight: 'touch',
      paddingBlock: 'sm',
      borderTop: 'hairline',
      textAlign: 'start',
      textDecoration: 'none',
      color: 'heading',
      transition: 'interactive',
      _hover: { color: 'action' },
      _focusVisible: { outline: 'focus', outlineOffset: 'focusInset' },
      '&[aria-current=true]': { color: 'highlight' },
    },
    title: { textStyle: 'body', color: 'inherit' },
    year: {
      flexShrink: '0',
      textStyle: 'label',
      color: 'muted',
      fontVariantNumeric: 'tabular-nums',
    },
  },
})
