import { sva } from 'styled-system/css'

/**
 * Calendar — co-located slot recipe.
 *
 * The date-by-date programme as a dark schedule board: header + counts, an
 * "Ongoing" exhibition card grid, the day-by-day agenda timeline, the NOW
 * marker, finished-edition recap + archive disclosure. Raw grays are the
 * documented dark-board exceptions; the card/gallery image filters are inlined
 * (were legacy `--card-*`/`--gallery-*` vars). State lives on data attributes:
 * `data-past`/`data-now` (runs/days), `data-on` (past toggle), `data-poster`
 * (event rows). The agenda's marker column is the `--marker-col` custom prop,
 * set responsively on the section.
 */
export const calendar = sva({
  slots: [
    'section',
    'inner',
    'layout',
    'header',
    'headerMain',
    'title',
    'meta',
    'metaYear',
    'metaDot',
    'counts',
    'count',
    'pastToggle',
    'band',
    'bandLabel',
    'runs',
    'run',
    'runMedia',
    'runContent',
    'runName',
    'runFoot',
    'runNow',
    'runRange',
    'empty',
    'emptyText',
    'emptyClear',
    'agenda',
    'day',
    'marker',
    'markerNode',
    'markerDay',
    'markerMeta',
    'markerMonth',
    'markerWeekday',
    'events',
    'event',
    'eventBody',
    'eventTop',
    'eventTime',
    'eventName',
    'nameButton',
    'eventDesc',
    'poster',
    'posterTag',
    'venue',
    'venueName',
    'venueParent',
    'chips',
    'chip',
    'now',
    'nowDot',
    'nowLabel',
    'nowDate',
    'nowRule',
    'recap',
    'recapLine',
    'recapMark',
    'recapFollow',
    'recapFollowLabel',
    'recapLinks',
    'recapLink',
    'archive',
    'archiveSummary',
    'archiveShow',
    'archiveHide',
    'archiveCount',
    'archiveChevron',
    'archivePanel',
  ],
  base: {
    section: {
      layerStyle: 'section',
      background: 'black',
      color: 'white',
      // Shared links land on #program; offset past the tall top padding.
      scrollMarginTop: 'calc(token(spacing.lg) - token(spacing.sectionY))',
      // Agenda date-marker column width; scales up with the type.
      '--marker-col': '84px',
      md: { '--marker-col': '132px' },
      lg: { '--marker-col': '168px' },
      xl: { '--marker-col': '144px' },
      '2xl': { '--marker-col': '160px' },
    },
    inner: { layerStyle: 'sectionInner' },
    layout: { minWidth: 0 },

    header: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 'md',
      marginBottom: 'xl',
    },
    headerMain: { minWidth: 0 },
    title: { textStyle: 'sectionTitle', marginBottom: 0 },
    meta: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: '12px',
      marginTop: 'md',
      fontFamily: 'body',
      fontSize: 'xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'body',
      md: { fontSize: 'sm' },
    },
    metaYear: { color: 'highlight' },
    metaDot: { width: '4px', height: '4px', background: 'gray.700', borderRadius: 'circle' },

    counts: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 'md',
      marginTop: 'sm',
    },
    count: {
      fontFamily: 'body',
      fontSize: 'xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'white',
      fontVariantNumeric: 'tabular-nums',
    },
    pastToggle: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      minHeight: '32px',
      padding: '6px 12px',
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'gray.300',
      background: 'transparent',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'gray.700',
      cursor: 'pointer',
      fontVariantNumeric: 'tabular-nums',
      transition:
        'color {durations.fast} {easings.quint}, border-color {durations.fast} {easings.quint}, background {durations.fast} {easings.quint}',
      _hover: { color: 'white', borderColor: 'white' },
      _focusVisible: { outline: '2px solid token(colors.highlight)', outlineOffset: '2px' },
      // On → the chartreuse "active" fill.
      '&[data-on=true]': {
        color: 'black',
        background: 'highlight',
        borderColor: 'highlight',
        _hover: { color: 'black', background: 'highlight', borderColor: 'highlight' },
      },
      '@media (prefers-reduced-motion: reduce)': { transition: 'none' },
    },

    // ---- Ongoing band — exhibition card grid ----
    band: {
      marginBottom: '2xl',
      paddingTop: 'lg',
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: 'divider',
    },
    bandLabel: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'wide',
      fontWeight: 'semibold',
      color: 'highlight',
      marginBottom: 'md',
    },
    runs: {
      listStyle: 'none',
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 300px), 1fr))',
      gap: 'md',
    },
    run: {
      display: 'flex',
      flexDirection: 'column',
      background: 'black',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'divider',
      position: 'relative',
      // Gradient hover ring (masked to the 1px edge).
      _before: {
        content: '""',
        position: 'absolute',
        inset: 0,
        padding: '0.5px',
        background:
          'linear-gradient(90deg, token(colors.action) 0%, token(colors.highlight) 50%, token(colors.action) 100%)',
        backgroundSize: '200% 100%',
        WebkitMask: 'linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)',
        WebkitMaskComposite: 'xor',
        maskComposite: 'exclude',
        opacity: 0,
        zIndex: 2,
        pointerEvents: 'none',
        transition: 'opacity {durations.normal} ease',
      },
      _hover: {
        '&::before': { opacity: 1, animation: 'gradientBorderShift 2s linear infinite' },
        '& img': { filter: 'grayscale(30%) brightness(1)', transform: 'scale(1.03)' },
        '& a': { color: 'white' },
      },
      '& a:focus-visible': { color: 'white' },
      // On-now exhibition — pink border lifts it out of the grid.
      '&[data-now=true]': { borderColor: 'action' },
      '&[data-now=true]:hover': { borderColor: 'action' },
      // Past de-emphasis (live edition only).
      '&[data-past=true]': {
        opacity: 0.42,
        transition: 'opacity {durations.normal} {easings.quint}',
      },
      '&[data-past=true]:hover': { opacity: 1 },
      '@media (prefers-reduced-motion: reduce)': {
        '&:hover::before': { animation: 'none' },
      },
    },
    runMedia: {
      position: 'relative',
      aspectRatio: '3 / 2',
      overflow: 'hidden',
      background: 'gray.800',
      '& img': {
        objectFit: 'cover',
        filter: 'grayscale(100%) brightness(0.7)',
        transition:
          'filter {durations.medium} {easings.quint}, transform {durations.medium} {easings.quint}',
      },
    },
    runContent: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'sm',
      padding: 'md',
      flex: 1,
      minWidth: 0,
    },
    runName: {
      fontFamily: 'body',
      fontWeight: 'bold',
      fontSize: 'base',
      lineHeight: 'tight',
      letterSpacing: 'tight',
      color: 'gray.200',
    },
    runFoot: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: '12px',
      marginTop: 'auto',
      paddingTop: 'sm',
    },
    runNow: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'action',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '7px',
      _before: {
        content: '""',
        width: '7px',
        height: '7px',
        borderRadius: 'circle',
        background: 'action',
        animation: 'pulse 2s {easings.quint} infinite',
      },
      '@media (prefers-reduced-motion: reduce)': { _before: { animation: 'none' } },
    },
    runRange: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      color: 'muted',
    },

    // ---- Empty state ----
    empty: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: 'md',
      paddingBlock: '2xl',
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: 'divider',
    },
    emptyText: {
      fontFamily: 'display',
      fontSize: 'lg',
      lineHeight: 'tight',
      color: 'gray.300',
    },
    emptyClear: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'white',
      background: 'transparent',
      border: 'none',
      paddingBottom: '3px',
      borderBottomWidth: '1px',
      borderBottomStyle: 'solid',
      borderBottomColor: 'gray.700',
      cursor: 'pointer',
      transition:
        'color {durations.fast} {easings.quint}, border-color {durations.fast} {easings.quint}',
      _hover: { color: 'action', borderColor: 'action' },
      _focusVisible: { outline: '2px solid token(colors.highlight)', outlineOffset: '2px' },
    },

    // ---- Agenda timeline ----
    agenda: {
      listStyle: 'none',
      position: 'relative',
      // Timeline spine + marker column from tablet up.
      md: {
        _before: {
          content: '""',
          position: 'absolute',
          top: '8px',
          bottom: '8px',
          left: 'var(--marker-col)',
          width: '1px',
          background: 'divider',
        },
      },
    },
    day: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      paddingBlock: 'lg',
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: 'divider',
      _first: { borderTopWidth: 0, paddingTop: 0 },
      '&[data-past=true]': {
        opacity: 0.42,
        transition: 'opacity {durations.normal} {easings.quint}',
      },
      '&[data-past=true]:hover': { opacity: 1 },
      md: {
        display: 'grid',
        gridTemplateColumns: 'var(--marker-col) 1fr',
        gap: 0,
        alignItems: 'start',
        position: 'relative',
      },
      xl: { paddingBlock: 'md' },
    },
    marker: {
      display: 'flex',
      alignItems: 'baseline',
      gap: '12px',
      md: {
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: '6px',
        paddingRight: 'lg',
        textAlign: 'right',
        position: 'sticky',
        top: 'lg',
      },
    },
    markerNode: {
      display: 'none',
      md: {
        display: 'block',
        position: 'absolute',
        right: '-4px',
        top: '9px',
        width: '8px',
        height: '8px',
        background: 'white',
        borderRadius: 'circle',
      },
    },
    markerDay: {
      fontFamily: 'display',
      fontSize: '3xl',
      lineHeight: '0.8',
      color: 'white',
      fontVariantNumeric: 'tabular-nums',
      md: { fontSize: '2xl' },
    },
    markerMeta: {
      display: 'flex',
      alignItems: 'baseline',
      gap: '8px',
      fontFamily: 'body',
      fontSize: 'xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      md: { flexDirection: 'column', alignItems: 'flex-end', gap: '2px' },
    },
    markerMonth: { color: 'muted' },
    markerWeekday: { color: 'action' },
    events: {
      listStyle: 'none',
      display: 'flex',
      flexDirection: 'column',
      md: { paddingLeft: 'lg' },
    },

    // ---- Event row ----
    event: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'md',
      paddingBlock: 'md',
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: 'divider',
      position: 'relative',
      _first: { borderTopWidth: 0 },
      _hover: {
        '& a': { color: 'action' },
        '& img': { filter: 'grayscale(0%) contrast(1)', transform: 'scale(1.03)' },
      },
    },
    eventBody: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'sm',
      minWidth: 0,
      // Reserve the hover-float poster's column on poster rows (wide screens).
      '@media (hover: hover) and (pointer: fine) and (min-width: 1280px)': {
        '[data-poster=true] &': { paddingRight: 'calc(220px + token(spacing.lg))' },
      },
    },
    eventTop: { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '10px' },
    eventTime: {
      fontFamily: 'display',
      fontSize: 'sm',
      color: 'white',
      fontVariantNumeric: 'tabular-nums',
      letterSpacing: 'subtle',
    },
    eventName: {
      fontFamily: 'body',
      fontWeight: 'bold',
      fontSize: 'base',
      lineHeight: 'tight',
      letterSpacing: 'tight',
      color: 'white',
    },
    // The name link; its ::after stretches the hit target over the whole row.
    nameButton: {
      font: 'inherit',
      color: 'inherit',
      textAlign: 'left',
      textDecoration: 'none',
      background: 'none',
      border: 'none',
      padding: 0,
      cursor: 'pointer',
      transition: 'color {durations.fast} {easings.quint}',
      _after: { content: '""', position: 'absolute', inset: 0, zIndex: 1 },
      _focusVisible: {
        color: 'action',
        outline: '2px solid token(colors.highlight)',
        outlineOffset: '3px',
      },
      '@media (prefers-reduced-motion: reduce)': { transition: 'none' },
    },
    eventDesc: {
      fontFamily: 'body',
      fontSize: 'sm',
      lineHeight: 'body',
      color: 'body',
      maxWidth: '64ch',
      // Two-line teaser; Panda's lineClamp expands the full -webkit-box clamp.
      lineClamp: '2',
    },
    // Touch/narrow: inline portrait thumbnail. Wide hover-capable: float (below).
    poster: {
      position: 'relative',
      aspectRatio: '3 / 4',
      width: '100%',
      maxWidth: '260px',
      overflow: 'hidden',
      background: 'gray.800',
      '& img': {
        objectFit: 'cover',
        filter: 'grayscale(100%) contrast(1.1)',
        transition:
          'filter {durations.medium} {easings.quint}, transform {durations.medium} {easings.quint}',
      },
      '@media (hover: hover) and (pointer: fine) and (min-width: 1280px)': {
        position: 'absolute',
        top: 'md',
        right: 0,
        width: '220px',
        maxWidth: 'none',
        opacity: 0,
        transform: 'translateX(20px)',
        transition:
          'opacity {durations.normal} {easings.expo}, transform {durations.normal} {easings.expo}',
        pointerEvents: 'none',
        zIndex: 3,
        '[data-poster=true]:hover &': { opacity: 1, transform: 'translateX(0)' },
      },
      '@media (hover: hover) and (pointer: fine) and (min-width: 1280px) and (prefers-reduced-motion: reduce)':
        {
          transition: 'opacity {durations.normal} {easings.quint}',
          transform: 'none',
          '[data-poster=true]:hover &': { transform: 'none' },
        },
    },
    posterTag: {
      display: 'none',
      alignItems: 'center',
      gap: '6px',
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'muted',
      transition: 'color {durations.fast} {easings.quint}',
      _before: { content: '""', width: '7px', height: '9px', background: 'currentColor' },
      '@media (hover: hover) and (pointer: fine) and (min-width: 1280px)': {
        display: 'inline-flex',
        '[data-poster=true]:hover &': { color: 'action' },
      },
    },

    // ---- Venue line + type chips (runs + events) ----
    venue: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: '8px',
      fontFamily: 'body',
      fontSize: 'xs',
    },
    venueName: {
      color: 'gray.300',
      textTransform: 'uppercase',
      letterSpacing: 'subtle',
      fontWeight: 'medium',
    },
    venueParent: {
      color: 'muted',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontSize: '2xs',
      _before: { content: '"↳ "' },
    },
    chips: { listStyle: 'none', display: 'flex', flexWrap: 'wrap', gap: '6px' },
    chip: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'highlight',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'highlightFaint',
      padding: '3px 9px',
      lineHeight: '1.4',
    },

    // ---- NOW marker ----
    now: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      paddingBlock: 'md',
      listStyle: 'none',
      md: { marginLeft: 'var(--marker-col)', paddingLeft: 'lg' },
    },
    nowDot: {
      width: '9px',
      height: '9px',
      borderRadius: 'circle',
      background: 'action',
      boxShadow: '0 0 0 0 color-mix(in srgb, var(--colors-action) 70%, transparent)',
      animation: 'pulse 2s {easings.quint} infinite',
      flexShrink: 0,
      '@media (prefers-reduced-motion: reduce)': { animation: 'none' },
    },
    nowLabel: {
      fontFamily: 'display',
      fontSize: 'sm',
      textTransform: 'uppercase',
      letterSpacing: 'subtle',
      color: 'action',
    },
    nowDate: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      color: 'muted',
    },
    nowRule: {
      flex: 1,
      height: '1px',
      background: 'linear-gradient(to right, token(colors.action), transparent)',
    },

    // ---- Finished-edition recap ----
    recap: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: 'md',
      marginTop: 'sm',
    },
    recapLine: { fontFamily: 'body', fontSize: 'base', lineHeight: 'body', color: 'body' },
    recapMark: { color: 'white', fontWeight: 'semibold' },
    recapFollow: { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 'md' },
    recapFollowLabel: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'muted',
    },
    recapLinks: { listStyle: 'none', display: 'flex', flexWrap: 'wrap', gap: 'md' },
    recapLink: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '6px',
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'white',
      textDecoration: 'none',
      paddingBottom: '2px',
      borderBottomWidth: '1px',
      borderBottomStyle: 'solid',
      borderBottomColor: 'gray.700',
      transition:
        'color {durations.fast} {easings.quint}, border-color {durations.fast} {easings.quint}',
      _hover: { color: 'action', borderColor: 'action' },
      _focusVisible: { outline: '2px solid token(colors.highlight)', outlineOffset: '2px' },
    },

    // ---- Finished-edition archive disclosure ----
    archive: { borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'divider' },
    archiveSummary: {
      display: 'flex',
      alignItems: 'center',
      gap: 'md',
      paddingBlock: 'lg',
      cursor: 'pointer',
      listStyle: 'none',
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      fontWeight: 'semibold',
      color: 'action',
      '&::-webkit-details-marker': { display: 'none' },
      _focusVisible: { outline: '2px solid token(colors.highlight)', outlineOffset: '2px' },
    },
    // Underline just the label on hover (the count stays plain).
    archiveShow: {
      'summary:hover &': { textDecoration: 'underline', textUnderlineOffset: '3px' },
      '[open] &': { display: 'none' },
    },
    archiveHide: {
      display: 'none',
      'summary:hover &': { textDecoration: 'underline', textUnderlineOffset: '3px' },
      '[open] &': { display: 'inline' },
    },
    archiveCount: { color: 'muted', fontVariantNumeric: 'tabular-nums' },
    archiveChevron: {
      marginLeft: 'auto',
      color: 'inherit',
      transition: 'transform {durations.normal} {easings.quint}',
      '[open] &': { transform: 'rotate(180deg)' },
      '@media (prefers-reduced-motion: reduce)': { transition: 'none' },
    },
    archivePanel: { paddingTop: 'md', paddingBottom: 'lg' },
  },
})
