import { sva } from 'styled-system/css'

export const credits = sva({
  slots: [
    'ledger',
    'wall',
    'tile',
    'link',
    'mark',
    'row',
    'band',
    'cell',
    'accent',
    'value',
    'detail',
    'run',
  ],
  base: {
    ledger: {
      width: 'full',
    },
    wall: {
      display: 'flex',
      width: 'full',
      paddingBlock: 'lg',
      borderBottom: 'hairline',
      md: { paddingBlock: 'xl' },
    },
    tile: {
      flex: 'none',
      display: 'flex',
      alignItems: 'center',
      minHeight: '[56px]',
      md: { minHeight: '[76px]' },
    },
    link: { display: 'inline-flex', minWidth: '0', pressable: 'inline' },
    mark: {
      maxWidth: 'full',
      width: 'auto',
      height: '[calc(56px * var(--mark-scale, 1))]',
      objectFit: 'contain',
      objectPosition: 'left',
      filter: '[token(assets.grayscaleFull)]',
      transition: 'develop',
      _hover: { filter: '[none]' },
      md: { height: '[calc(76px * var(--mark-scale, 1))]' },
    },
    row: {
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr)',
      rowGap: 'xs',
      paddingBlock: 'md',
      borderBottom: 'hairline',
      md: {
        gridTemplateColumns: '[minmax(140px, 16%) minmax(0, 1fr)]',
        columnGap: 'lg',
        alignItems: 'baseline',
      },
    },
    band: {
      md: {
        display: 'grid',
        gridTemplateColumns: '[repeat(2, minmax(0, 1fr))]',
        columnGap: 'lg',
        rowGap: 'md',
        paddingBlock: 'md',
      },
      lg: { gridTemplateColumns: '[repeat(3, minmax(0, 1fr))]' },
      '2xl': { gridTemplateColumns: '[repeat(6, minmax(0, 1fr))]' },
    },
    cell: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      rowGap: 'xs',
      paddingBlock: 'md',
      borderBottom: 'hairline',
      _last: { borderBottom: '[none]' },
      md: { paddingBlock: '0', borderBottom: '[none]' },
    },
    accent: { color: 'action' },
    value: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      minWidth: '0',
    },
    detail: {
      whiteSpace: 'pre-line',
    },
    run: {
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'baseline',
      columnGap: '0',
      rowGap: 'xs',
      maxWidth: 'measure',
      '& span': {
        display: 'inline-flex',
        alignItems: 'center',
        whiteSpace: 'nowrap',
      },
      '& span:not(:last-child)::after': {
        content: '""',
        flex: 'none',
        width: '[3px]',
        height: '[3px]',
        marginInline: 'sm',
        borderRadius: 'circle',
        background: 'action',
      },
    },
  },
  variants: {
    wrap: {
      true: { run: { '& span': { whiteSpace: 'normal' } } },
      false: {},
    },
  },
  defaultVariants: { wrap: false },
})
