import { sva } from 'styled-system/css'

export const hero = sva({
  slots: [
    'hero',
    'inner',
    'head',
    'mast',
    'prefix',
    'plate',
    'frame',
    'image',
    'thumb',
    'ledger',
    'row',
    'rowLabel',
    'rowValue',
  ],
  base: {
    hero: {
      layerStyle: 'pageHero',
      paddingInline: 'gutter',
      position: 'relative',
      minHeight: { base: '[calc(100svh - 80px)]', lg: '[calc(100svh - 120px)]' },
      display: 'flex',
      flexDirection: 'column',
      overflow: 'hidden',
    },
    inner: {
      position: 'relative',
      zIndex: '1',
      flex: '1',
      width: 'full',
      maxWidth: 'maxWidth',
      marginInline: 'auto',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      gap: '2xl',
    },

    head: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: 'md',
      minWidth: '0',
      animationStyle: 'enter',
    },
    mast: {
      margin: '0',
      display: 'flex',
      alignItems: 'baseline',
      flexWrap: 'wrap',
      columnGap: '[0.25em]',
    },
    prefix: { color: '[currentColor]' },

    plate: {
      position: 'absolute',
      inset: '0',
      zIndex: '0',
      _portrait: {
        position: 'relative',
        inset: 'auto',
        aspectRatio: '1 / 1',
        marginBottom: 'xl',
      },
    },
    frame: {
      position: 'absolute',
      inset: '0',
      overflow: 'hidden',
      background: 'gray.900',
      filter: '[token(assets.color)]',
    },
    image: {
      objectFit: 'cover',
      objectPosition: 'right',
      _portrait: { display: 'none' },
    },
    thumb: {
      objectFit: 'cover',
      display: 'none',
      _portrait: { display: 'block' },
    },

    ledger: {
      margin: '0',
      width: 'fit',
      maxWidth: 'narrowColumn',
      animationStyle: 'enter',
      animationDelay: 'stagger',
      _portrait: { width: 'full' },
    },
    row: {
      display: 'grid',
      gridTemplateColumns: '[64px minmax(0, 1fr)]',
      columnGap: 'md',
      alignItems: 'baseline',
      paddingBlock: 'sm',
      paddingRight: 'md',
      borderBottomStyle: 'solid',
      borderBottomWidth: 'hairlineThin',
      borderBottomColor: '[color-mix(in srgb, currentColor 40%, transparent)]',
      _last: { borderBottomWidth: '0' },
      _portrait: { paddingRight: '0' },
    },
    rowLabel: { margin: '0' },
    rowValue: { margin: '0', overflowWrap: 'anywhere' },
  },
  variants: {
    ink: {
      black: { inner: { color: 'black', _portrait: { color: 'white' } } },
      white: { inner: { color: 'white' } },
    },
  },
  defaultVariants: { ink: 'white' },
})
