import { sva } from 'styled-system/css'

/**
 * Press page — co-located slot recipe.
 *
 * Dark page: media-kit strip, then two link registers (appearances, releases)
 * as hairline-separated rows whose title + arrow warm to the accent on hover.
 * Shared hero header → `PageHero`; the `.appTag` pill → `<Badge>`. The unused
 * legacy `contact*` / `kitDeck` rules are dropped (the shell renders no contact
 * block or kit deck). Row hovers drive from the link `<a>` via `a:hover &`.
 */
export const pressPage = sva({
  slots: [
    'page',
    'kitSection',
    'kitHeader',
    'kitTitle',
    'appearances',
    'appearancesInner',
    'appList',
    'appRow',
    'appLink',
    'appType',
    'appBody',
    'appText',
    'appAside',
    'appTitle',
    'appExcerpt',
    'appDate',
    'appArrow',
    'releases',
    'releasesInner',
    'releaseList',
    'releaseRow',
    'releaseLink',
    'releaseId',
    'releaseIcon',
    'releaseBody',
    'releaseTitle',
    'releaseMeta',
    'releaseAction',
  ],
  base: {
    page: { background: 'black', color: 'white' },

    kitSection: { paddingTop: '3xl', paddingInline: 'content', paddingBottom: '4xl' },
    kitHeader: { maxWidth: 'maxWidth', marginInline: 'auto', marginBottom: '2xl' },
    kitTitle: { textStyle: 'sectionTitle', marginBottom: 'md' },

    appearances: { paddingTop: '3xl', paddingInline: 'content', paddingBottom: '4xl' },
    appearancesInner: { maxWidth: 'maxWidth', marginInline: 'auto' },
    appList: { listStyle: 'none', padding: '0', margin: '0' },
    appRow: { '& + &': { borderTop: '1px solid token(colors.borderDark)' } },
    appLink: {
      display: 'grid',
      gridTemplateColumns: '1fr auto',
      gridTemplateAreas: '"type aside" "body body"',
      alignItems: 'center',
      columnGap: { base: 'md', md: 'lg' },
      rowGap: 'sm',
      paddingBlock: 'lg',
      textDecoration: 'none',
      color: 'inherit',
    },
    appType: {
      gridArea: 'type',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      fontFamily: 'body',
      fontSize: { base: 'xs', md: 'sm' },
      letterSpacing: 'label',
      color: 'body',
      '& svg': { color: 'highlight', flexShrink: '0' },
    },
    appBody: {
      gridArea: 'body',
      display: 'flex',
      alignItems: 'center',
      gap: 'md',
      minWidth: '0',
    },
    appText: { flex: '1', minWidth: '0', display: 'block' },
    appAside: {
      gridArea: 'aside',
      display: 'inline-flex',
      alignItems: 'center',
      gap: 'sm',
      alignSelf: 'center',
      justifySelf: 'end',
    },
    appTitle: {
      display: 'block',
      fontFamily: 'display',
      fontSize: { base: 'md', md: 'xl' },
      lineHeight: 'heading',
      color: 'white',
      transition: 'color {durations.normal} ease',
      'a:hover &': { color: 'action' },
    },
    appExcerpt: {
      display: 'block',
      fontFamily: 'body',
      fontSize: 'xs',
      lineHeight: 'body',
      color: 'muted',
      marginTop: '4px',
      maxWidth: '60ch',
    },
    appDate: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      color: 'muted',
      whiteSpace: 'nowrap',
      fontVariantNumeric: 'tabular-nums',
    },
    appArrow: {
      flexShrink: '0',
      color: 'muted',
      display: 'inline-flex',
      transition: 'color {durations.normal} ease, transform {durations.normal} {easings.expo}',
      'a:hover &': { color: 'action', transform: 'translate(4px, -4px)' },
    },

    releases: { paddingTop: '3xl', paddingInline: 'content', paddingBottom: '4xl' },
    releasesInner: { maxWidth: 'maxWidth', marginInline: 'auto' },
    releaseList: { listStyle: 'none', padding: '0', margin: '0' },
    releaseRow: { '& + &': { borderTop: '1px solid token(colors.borderDark)' } },
    releaseLink: {
      display: 'grid',
      gridTemplateColumns: 'auto auto 1fr auto',
      alignItems: 'center',
      gap: 'md',
      paddingBlock: 'lg',
      textDecoration: 'none',
      color: 'inherit',
    },
    releaseId: { fontFamily: 'display', fontSize: 'xs', color: 'muted', width: '30px' },
    releaseIcon: { display: 'inline-flex', color: 'muted' },
    releaseBody: { display: 'flex', flexDirection: 'column', gap: '4px', minWidth: '0' },
    releaseTitle: {
      fontFamily: 'display',
      fontSize: { base: 'md', md: 'lg' },
      lineHeight: 'heading',
      textTransform: 'uppercase',
      color: 'white',
      transition: 'color {durations.normal} ease',
      'a:hover &': { color: 'action' },
    },
    releaseMeta: {
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'label',
      color: 'muted',
    },
    releaseAction: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      fontFamily: 'body',
      fontSize: '2xs',
      textTransform: 'uppercase',
      letterSpacing: 'wide',
      fontWeight: 'semibold',
      color: 'action',
      whiteSpace: 'nowrap',
    },
  },
})
