import { sva } from 'styled-system/css'

export const bellerHero = sva({
  slots: [
    'hero',
    'inner',
    'copy',
    'mast',
    'wordmark',
    'ledger',
    'row',
    'rowLabel',
    'rowValue',
    'visual',
    'visualImg',
  ],
  base: {
    hero: {
      background: 'var(--beller-hero-bg)',
      color: 'black',
      paddingInline: 'gutter',
      paddingBlock: { base: 'xl', lg: '2xl' },
      overflow: 'hidden',
      md: {
        display: 'flex',
        flexDirection: 'column',
        minHeight: '[calc(token(sizes.heroFold) - token(sizes.bellerBar) * 0.6)]',
      },
    },
    inner: {
      display: 'grid',
      gridTemplateColumns: { base: '1fr', md: '5fr 6fr' },
      alignItems: 'center',
      gap: { base: 'xl', lg: '2xl' },
      width: 'full',
      maxWidth: 'maxWidth',
      marginInline: 'auto',
      md: { flex: '1' },
    },
    copy: {
      minWidth: '0',
      display: { base: 'contents', md: 'flex' },
      flexDirection: 'column',
      gap: 'xl',
    },
    mast: { margin: '0', animationStyle: 'enter' },
    wordmark: {
      display: 'block',
      width: 'auto',
      height: 'auto',
      maxWidth: '[min(100%, 560px)]',
      maxHeight: { base: '[16svh]', md: '[30svh]' },
    },
    ledger: {
      order: '1',
      margin: '0',
      maxWidth: 'narrowColumn',
      animationStyle: 'enter',
      animationDelay: 'stagger',
    },
    row: {
      display: 'grid',
      gridTemplateColumns: '[7rem minmax(0, 1fr)]',
      alignItems: 'baseline',
      gap: 'md',
      paddingBlock: 'sm',
      borderTop: '[1px solid currentColor]',
      _last: { borderBottom: '[1px solid currentColor]' },
    },
    rowLabel: { margin: '0' },
    rowValue: { margin: '0', fontWeight: '[600]', overflowWrap: 'anywhere' },
    visual: {
      position: 'relative',
      width: { base: '[76%]', md: 'full' },
      justifySelf: 'center',
      aspectRatio: '[var(--beller-visual-ratio)]',
      md: { aspectRatio: 'auto', alignSelf: 'stretch' },
      animationStyle: 'enter.zoom',
    },
    visualImg: { objectFit: 'contain' },
  },
})
