import { sva } from 'styled-system/css'

export const bellerHero = sva({
  slots: [
    'hero',
    'inner',
    'copy',
    'mast',
    'wordmark',
    'ledger',
    'row',
    'rowLabel',
    'rowValue',
    'visual',
    'visualImg',
  ],
  base: {
    hero: {
      background: 'var(--beller-hero-bg)',
      color: 'black',
      paddingInline: 'gutter',
      paddingBlock: { base: 'xl', lg: '2xl' },
      overflow: 'hidden',
      md: {
        display: 'flex',
        flexDirection: 'column',
        minHeight: 'min(calc(token(sizes.heroFold) - token(sizes.bellerBar) * 0.6), 50vw)',
      },
    },
    inner: {
      display: 'grid',
      gridTemplateColumns: { base: '1fr', md: 'minmax(max-content, 5fr) 6fr' },
      alignItems: 'center',
      gap: { base: 'xl', lg: '2xl' },
      width: '100%',
      maxWidth: 'maxWidth',
      marginInline: 'auto',
      md: { flex: '1' },
    },
    copy: {
      minWidth: '0',
      display: { base: 'contents', md: 'flex' },
      flexDirection: 'column',
      gap: 'xl',
    },
    mast: { margin: '0', animationStyle: 'enter' },
    wordmark: {
      display: 'block',
      width: 'auto',
      height: 'auto',
      maxWidth: {
        base: 'min(100%, 560px)',
        md: 'min(60%, 336px)',
        '4xl': 'min(66%, 370px)',
      },
      maxHeight: { base: '10.24svh', md: '18svh', '4xl': '19.8svh' },
      _landscapePhone: { maxHeight: '25.74svh' },
    },
    ledger: {
      order: '1',
      margin: '0',
      maxWidth: 'narrowColumn',
      display: 'grid',
      gridTemplateColumns: 'max-content minmax(0, 1fr)',
      columnGap: 'md',
      animationStyle: 'enter',
      animationDelay: 'stagger',
    },
    row: {
      gridColumn: '1 / -1',
      display: 'grid',
      gridTemplateColumns: 'subgrid',
      alignItems: 'baseline',
      paddingBlock: 'sm',
      borderTop: '1px solid currentColor',
      _last: { borderBottom: '1px solid currentColor' },
    },
    rowLabel: { margin: '0' },
    rowValue: { margin: '0', fontWeight: '600', overflowWrap: 'anywhere' },
    visual: {
      position: 'relative',
      width: { base: '76%', md: 'auto' },
      justifySelf: { base: 'center', md: 'stretch' },
      aspectRatio: 'var(--beller-visual-ratio)',
      md: {
        aspectRatio: 'auto',
        alignSelf: 'stretch',
        marginBlock: '-xl',
        marginRight: '-gutter',
      },
      lg: { marginBlock: '-2xl' },
      animationStyle: 'enterZoom',
    },
    visualImg: { objectFit: 'contain' },
  },
})
