import { sva } from 'styled-system/css'

export const bellerHero = sva({
  slots: [
    'hero',
    'inner',
    'copy',
    'zsb',
    'zsbLogo',
    'mast',
    'wordmark',
    'ledger',
    'row',
    'rowLabel',
    'rowValue',
    'visual',
    'visualImg',
  ],
  base: {
    hero: {
      background: 'var(--beller-hero-bg)',
      color: 'black',
      paddingInline: 'gutter',
      paddingBlock: { base: 'xl', lg: '2xl' },
      overflow: 'hidden',
    },
    inner: {
      display: 'grid',
      gridTemplateColumns: { base: '1fr', lg: '5fr 6fr' },
      alignItems: 'center',
      gap: { base: 'xl', lg: '2xl' },
      width: 'full',
      maxWidth: 'maxWidth',
      marginInline: 'auto',
      minHeight: { lg: '[calc(100svh - 120px)]' },
    },
    copy: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'xl',
      animationStyle: 'enter',
    },
    zsb: {
      display: 'inline-flex',
      width: 'fit',
      _focusVisible: { outline: 'focus', outlineOffset: '[4px]' },
    },
    zsbLogo: { width: '[56px]', height: 'auto', md: { width: '[72px]' } },
    mast: { margin: '0' },
    wordmark: { width: 'full', height: 'auto', maxWidth: '[560px]' },
    ledger: { margin: '0', maxWidth: 'narrowColumn' },
    row: {
      display: 'grid',
      gridTemplateColumns: '[7rem 1fr]',
      gap: 'md',
      paddingBlock: 'sm',
      borderTop: '[1px solid currentColor]',
      _last: { borderBottom: '[1px solid currentColor]' },
    },
    rowLabel: { margin: '0' },
    rowValue: { margin: '0', fontWeight: '[600]' },
    visual: {
      position: 'relative',
      width: 'full',
      aspectRatio: '[1620 / 1906]',
      maxHeight: { lg: '[calc(100svh - 160px)]' },
      animationStyle: 'enter.zoom',
    },
    visualImg: { objectFit: 'contain' },
  },
})
