import { sva } from 'styled-system/css'

export const homePage = sva({
  slots: [
    'panel',
    'hero',
    'heroRail',
    'heroVisual',
    'heroPanel',
    'heroTitle',
    'editionsLayout',
    'editionsHead',
    'editionsSubtext',
    'editionsLedger',
    'editionsStat',
    'editionsWall',
    'editionTile',
    'editionPlate',
    'editionImage',
    'editionMeta',
    'editionPrefix',
    'editionLines',
    'editionThemeRow',
    'upcomingLead',
    'upcomingEyebrow',
    'upcomingBadge',
    'lastEdition',
    'lastEditionMedia',
  ],
  base: {
    panel: { width: '100%', scrollMarginTop: 'token(sizes.nav)' },
    hero: {
      layerStyle: 'pageHero',
      position: 'relative',
      width: '100%',
      paddingInline: 'gutter',
      overflow: 'hidden',
      minHeight: 'svh',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      lg: {
        paddingTop: 'calc(token(sizes.nav) + token(spacing.xl) + token(spacing.md))',
        paddingBottom: 'calc(token(spacing.2xl) + token(spacing.md))',
        minHeight: 'min(calc(100svh - 90px), 70vw)',
      },
    },
    heroRail: {
      position: 'relative',
      maxWidth: 'maxWidth',
      marginInline: 'auto',
      width: '100%',
      lg: { marginTop: '100px' },
      '2xl': { marginTop: '150px' },
    },
    heroVisual: {
      order: '2',
      position: 'relative',
      width: '100%',
      minWidth: '0',
      lg: {
        gridColumn: '1 / -1',
        gridRow: '1',
        zIndex: '0',
        // `width: full` pins the box to its grid track, so the negative margin shifts it instead of widening it.
        width: 'auto',
        marginRight:
          'calc((min(100vw - 2 * token(spacing.gutter), token(sizes.maxWidth)) - 100vw) / 2)',
      },
    },
    heroPanel: {
      order: '1',
      position: 'relative',
      minWidth: '0',
      lg: { gridColumn: '1', gridRow: '1', zIndex: '1', transform: 'translateY(-100px)' },
      '2xl': { transform: 'translateY(-150px)' },
    },
    heroTitle: {
      animationStyle: 'enter',
      animationDelay: 'stagger',
      width: 'min-content',
    },
    editionsLayout: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'xl',
      width: '100%',
      maxWidth: 'maxWidth',
      marginInline: 'auto',
      paddingInline: 'gutter',
    },
    editionsHead: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'lg',
      xl: {
        display: 'grid',
        gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 640px)',
        alignItems: 'end',
        columnGap: 'xl',
      },
    },
    editionsSubtext: {
      maxWidth: 'measure',
    },
    editionsLedger: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      maxWidth: '640px',
      borderTop: 'hairline',
    },
    editionsStat: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'xs',
      paddingTop: 'sm',
      paddingRight: 'md',
      fontVariantNumeric: 'tabular-nums',
      '& + &': { paddingLeft: 'md', borderLeft: 'hairline' },
    },
    editionsWall: {
      listStyle: 'none',
      display: 'grid',
      gridTemplateColumns: {
        base: 'minmax(0, 1fr)',
        md: 'repeat(2, minmax(0, 1fr))',
        lg: 'repeat(3, minmax(0, 1fr))',
      },
      columnGap: 'lg',
      rowGap: 'xl',
    },
    editionTile: {
      display: 'grid',
      gap: 'md',
      color: 'inherit',
      textDecoration: 'none',
      pressable: 'dim',
    },
    editionPlate: {
      position: 'relative',
      overflow: 'hidden',
      aspectRatio: { base: '3 / 2', md: '16 / 9', lg: '3 / 2' },
      '[aria-disabled] > &': { opacity: '0.5' },
    },
    editionImage: {
      objectFit: 'cover',
      filter: 'token(assets.color)',
      transition: 'develop',
      'a:hover &, a:focus-visible &': {
        filter: 'token(assets.colorHover)',
        transform: 'scale(1.05)',
      },
    },
    editionMeta: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'xs',
      paddingTop: 'sm',
      borderTop: 'hairline',
    },
    editionPrefix: {
      color: 'muted',
      transition: 'interactive',
      'a:hover &, a:focus-visible &': { color: 'action' },
    },
    editionLines: {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 'sm',
      fontVariantNumeric: 'tabular-nums',
    },
    editionThemeRow: {
      flexWrap: 'wrap',
    },
    upcomingLead: {
      alignItems: 'flex-start',
      minWidth: '0',
      lg: { flex: '1 1 0' },
    },
    upcomingEyebrow: {
      color: 'highlight',
    },
    upcomingBadge: {
      alignSelf: 'center',
      lg: { alignSelf: 'flex-start' },
    },
    lastEdition: {
      alignItems: 'flex-start',
      width: '100%',
      maxWidth: 'narrowColumn',
      lg: { flex: '0 0 42%', maxWidth: '460px' },
    },
    lastEditionMedia: { position: 'relative', width: '100%' },
  },
})
