import { defineSlotRecipe } from '@pandacss/dev'

export const carousel = defineSlotRecipe({
  className: 'carousel',
  jsx: ['Carousel'],
  description: 'Ark-backed stage and rail carousel contract',
  slots: [
    'root',
    'frame',
    'scrim',
    'counter',
    'counterNow',
    'counterTotal',
    'plate',
    'itemGroup',
    'item',
    'control',
    'trigger',
    'indicatorGroup',
    'indicator',
  ],
  base: {
    root: { position: 'relative', width: '100%', minWidth: 0 },
    frame: { position: 'relative', isolation: 'isolate' },
    itemGroup: {
      scrollbarWidth: 'none',
      scrollBehavior: 'smooth',
      '&::-webkit-scrollbar': { display: 'none' },
      '&[data-dragging]': { cursor: 'grabbing' },
      _motionReduce: { scrollBehavior: 'auto' },
    },
    item: { minWidth: 0 },
    control: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 'md',
      '& [data-carousel-arrows]': { display: 'flex', alignItems: 'center', gap: 'sm' },
    },
    // Shared by prev/next/autoplay — all three are the same 44px transparent
    // hit target with the same hover/focus treatment.
    trigger: {
      pressable: 'inline',
      width: 'touch',
      height: 'touch',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      border: 0,
      background: 'transparent',
      color: 'heading',
      cursor: 'pointer',
      _hover: { color: 'action' },
      _disabled: { opacity: 0.5, cursor: 'not-allowed' },
    },
    indicatorGroup: { display: 'flex', alignItems: 'center', gap: '10px' },
    indicator: {
      pressable: 'dim',
      width: '14px',
      height: '2px',
      padding: 0,
      border: 0,
      background: 'muted',
      cursor: 'pointer',
      '&[data-current]': { width: '28px', background: 'highlight' },
    },
  },
  variants: {
    mode: {
      stage: {
        root: { display: 'flex', flexDirection: 'column', gap: 'md' },
        frame: {
          _after: {
            content: '""',
            position: 'absolute',
            inset: '0',
            zIndex: '3',
            pointerEvents: 'none',
            border: 'hairline',
          },
        },
        scrim: {
          position: 'absolute',
          insetInline: '0',
          bottom: '0',
          height: '[42%]',
          zIndex: '1',
          pointerEvents: 'none',
          backgroundGradient: 'stageScrim',
        },
        counter: {
          position: 'absolute',
          left: '0',
          bottom: '0',
          zIndex: '2',
          display: 'flex',
          alignItems: 'baseline',
          gap: 'sm',
          padding: 'md',
        },
        counterNow: { textStyle: 'heading', color: 'heading', lineHeight: '1' },
        counterTotal: { textStyle: 'label', color: 'muted' },
        plate: {
          position: 'absolute',
          right: '0',
          bottom: '0',
          zIndex: '2',
          display: 'flex',
          alignItems: 'center',
          paddingInline: 'md',
          background: 'surface',
          borderTop: 'hairline',
          borderLeft: 'hairline',
        },
        control: { gap: 'md' },
        itemGroup: {
          width: '100%',
          aspectRatio: { base: '1 / 1', md: '16 / 9' },
          background: 'black',
        },
        item: {
          width: '100%',
          height: '100%',
          '& > [data-carousel-slide-content]': { width: '100%', height: '100%' },
        },
      },
      rail: {
        itemGroup: { cursor: 'grab', touchAction: 'pan-x' },
        control: { paddingInline: 'gutter' },
        item: { '& > [data-carousel-slide-content]': { height: '100%' } },
      },
    },
  },
  defaultVariants: { mode: 'rail' },
})
